#ifndef LUCENT_FAKE_EGLEXT_H
#define LUCENT_FAKE_EGLEXT_H
#define EGL_OPENGL_ES3_BIT_KHR 0x0040
#define EGL_CONTEXT_MAJOR_VERSION_KHR 0x3098
#define EGL_CONTEXT_MINOR_VERSION_KHR 0x30FB
typedef int64_t EGLnsecsANDROID;
typedef uint64_t EGLuint64KHR;
#define EGL_TIMESTAMPS_ANDROID 0x3430
#define EGL_COMPOSITE_INTERVAL_ANDROID 0x3432
#define EGL_DISPLAY_PRESENT_TIME_ANDROID 0x343A
#define EGL_TIMESTAMP_PENDING_ANDROID -2
#define EGL_TIMESTAMP_INVALID_ANDROID -1
typedef EGLBoolean (*PFNEGLGETNEXTFRAMEIDANDROIDPROC)(EGLDisplay, EGLSurface, EGLuint64KHR *);
typedef EGLBoolean (*PFNEGLGETFRAMETIMESTAMPSANDROIDPROC)(EGLDisplay, EGLSurface, EGLuint64KHR, EGLint, const EGLint *, EGLnsecsANDROID *);
typedef EGLBoolean (*PFNEGLGETFRAMETIMESTAMPSUPPORTEDANDROIDPROC)(EGLDisplay, EGLSurface, EGLint);
typedef EGLBoolean (*PFNEGLGETCOMPOSITORTIMINGANDROIDPROC)(EGLDisplay, EGLSurface, EGLint, const EGLint *, EGLnsecsANDROID *);
#endif
