#!/usr/bin/env python3
"""Generate Aps3eLocalizedStrings.java from the pinned aPS3e source.

aPS3e's native library reads every RPCS3 interface string from an environment
variable named after its localized_string_id key while it is being loaded, and
falls back to the key itself ("PROGRESS DIALOG COMPILING PPU MODULES") when the
variable is missing. The aPS3e app sets those variables from its strings.xml;
EmuFusion embeds the library without those resources, so it publishes the same
English strings itself (NativeAdapterSystemDirectory.prepareForOpen).

usage: generate_aps3e_localized_strings.py [--check]
"""
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'engines/build/sources/aps3e-b5ae1af50d5e2f3b705506e7380a4504e086840b/app/src/main'
OUTPUT = ROOT / 'unified-android/src/com/thorium/preview/game/Aps3eLocalizedStrings.java'


def android_unescape(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] == '"':
        value = value[1:-1]
    return re.sub(r'\\(.)', lambda m: {'n': '\n', 't': '\t'}.get(m.group(1), m.group(1)), value)


def java_literal(value):
    out = []
    for ch in value:
        if ch in '\\"':
            out.append('\\' + ch)
        elif ch == '\n':
            out.append('\\n')
        elif ch == '\t':
            out.append('\\t')
        elif ord(ch) < 0x20 or ord(ch) > 0x7e:
            out.append('\\u%04x' % ord(ch))
        else:
            out.append(ch)
    return '"' + ''.join(out) + '"'


def generate():
    keys = re.findall(r'WRAP\((\w+)\)',
                      (SOURCE / 'cpp/rpcs3/rpcs3/Emu/localized_string_id.inc').read_text())
    strings = {e.get('name'): android_unescape(''.join(e.itertext()))
               for e in ET.parse(SOURCE / 'res/values/strings.xml').getroot().iter('string')}
    missing = [k for k in keys if k not in strings]
    if missing:
        raise SystemExit('aPS3e keys without English strings: ' + ', '.join(missing))
    rows = ''.join('            %s, %s,\n' % (java_literal(k), java_literal(strings[k])) for k in keys)
    return ('package com.thorium.preview.game;\n\n'
            '/**\n'
            ' * English RPCS3 interface strings for the embedded aPS3e library, keyed by\n'
            ' * localized_string_id. Generated by tools/generate_aps3e_localized_strings.py\n'
            ' * from the pinned aPS3e source (GPL-2.0, see engines/compliance/aps3e); do not\n'
            ' * edit by hand.\n'
            ' */\n'
            'final class Aps3eLocalizedStrings {\n'
            '    private Aps3eLocalizedStrings() {}\n\n'
            '    /** Alternating key, value. */\n'
            '    static final String[] KEYS_AND_VALUES = {\n'
            + rows +
            '    };\n'
            '}\n')


if __name__ == '__main__':
    text = generate()
    if '--check' in sys.argv:
        sys.exit(0 if OUTPUT.read_text() == text else 'Aps3eLocalizedStrings.java is stale')
    OUTPUT.write_text(text)
    print('wrote', OUTPUT.relative_to(ROOT), text.count('\n'), 'lines')
